### ISSUE TITLE
Broken README link "follow the instructions for 5 minutes to awesome"

### ISSUE THREAD

**Issue by snej** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#102]
In `src/README.md` the link "[follow the instructions for 5 minutes to awesome](http://docs.couchbase.com/couchbase-lite/cbl-phonegap/#getting-started-in-5-minutes)" is broken.

Actually, should there be a file `src/README.md` at all? It looks like an out-of-date version of the main README; the main README doesn't have this broken link.

**Comment by jamiltz** [comment]
Updated in the commit above. Like you said, looks like the one in `src` wasn't updated but pretty sure they are both generated from the README in the plugin builder repo.  And it was also updated in that repo https://github.com/couchbaselabs/couchbase-lite-phonegap-plugin-builder/commit/54063c93ea462d0edb3eeea3bc34402b0a263f95 for when the plugin is re-generated and pushed to this repo (cc @pasin).
