### ISSUE TITLE
Support for 64bit 

### ISSUE THREAD

**Issue by kcljeff** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#17]
Will the plugin be updated to support 64bit framework? Got x86_64 error when try to build for 64bit machine in XCode.

**Comment by andpor** [comment]
Hi Vinay,

i have not been successfull in upgrading the plugin to the new version published in Github as I highlighted before.

However, manual adjustments worked.

Make sure your Frameworks list for CB Lite looks like what is in the attached. JavaScriptCore.framework is a standard iOS framework that you have to add manually in project settings.

![screen shot 2015-01-09 at 6 32 06 pm](https://cloud.githubusercontent.com/assets/10236571/5684195/7524c558-982e-11e4-8a84-8ab11b300003.png)

**Comment by vinaynb** [comment]
Thanks for the help @andpor that was really helpful. Will do and check as you said. 
About removing JavascriptCore.a file...i can see that file in that list right now...so i gotta remove it and add JavascriptCore.framework correct ?

**Comment by pasin** [comment]
I just tested upgrading the plugin from v1.0.3 to v1.0.3-64 bits and I didn't see any issues. I was able to run and archive the project. I tested both phonegap and cordova command. 

```
$phonegap plugin rm com.couchbase.lite.phonegap
$phonegap plugin add com.couchbase.lite.phonegap
```
You may need to do Product > Clean to clear previous cache before trying to run or archive. Sometime I do see some issues that the iOS project doesn't get updated properly when updating a plugin so I need to re-add the iOS platform as follows:
``
$phonegap platform rm ios
$phonegap platform add ios
``
You can replace the `phonegap` command above with the `cordova` command as well. As I don't think the latest plugin v1.0.3-64bits itself has any issues, I'm closing the ticket now. Feel free to add any more comments and we could re-open the issue anytime.

**Comment by pasin** [comment]
@vinaynb: Yes, to do that workaround, you will need to remove the link to JavascriptCore.a and add JavascriptCore.framework.

**Comment by andpor** [comment]
yes. 

     On Friday, January 9, 2015 6:57 PM, Vinay Bhinde <notifications@github.com> wrote:
   

 Thanks for the help @andpor that was really helpful. Will do and check as you said. 
About removing JavascriptCore.a file...i can see that file in that list right now...so i gotta remove it and add JavascriptCore.framework correct ?—
