### ISSUE TITLE
Cross-origin access errors with GapReload and Phonegap Developer App

### ISSUE THREAD

**Issue by AdamDz** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#38]
Couchbase Lite does not work with rapid development tools that implement live app reload and eliminate the compile and install step (i.e. calling `cordova run` every JS/HTML change). These tools include:
 [GapReload](https://github.com/fingerproof/cordova-plugin-gapreload) and Adobe's [PhoneGap Developer App](http://app.phonegap.com/). They work by redirecting the webview from a `file://` location to a server on the developer's machine started by `cordova serve`. 
When we try to connect to Couchbase Lite in such setup, an error is thrown:

> XMLHttpRequest cannot load http://lite.couchbase./temp. Origin http://192.168.1.104:8000 is not allowed by Access-Control-Allow-Origin.

The cross-resource origin policy is not applied when the embedded web application is served from the standard location using `file://`, but it is after the redirection to `http://`

A solution would be to add a header to HTTP responses returned by Couchbase Lite: 

```
Access-Control-Allow-Origin: *
```

**Comment by jamiltz** [comment]
we now have a version of LiteServ with CORS available for development purposes https://developer.couchbase.com/documentation/mobile/1.4/installation/phonegap/index.html#development-environment. Closing this ticket.

**Comment by swavans** [comment]
I'm still having this issue, is there a way to fix this?
