### ISSUE TITLE
Build preview plugin from current master

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#47]
One of PhoneGap Plugin user encounters performance issue with Android. We should provide the build from master couchbase-lite-java-core and couchbase-lite-android

**Comment by pasin** [comment]
http://cbfs-ext.hq.couchbase.com/builds/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-56.zip
