### ISSUE TITLE
window.cblite = undefined

### ISSUE THREAD

**Issue by sandraVicom** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#50]

**Comment by yueyingcui** [comment]
hi sandraVicom,

I have the same issue: window.cblite = undefined, and shows 'Couchbase Lite not installed' error. Could you tell me how did you fix it?

Thanks,
Yueying

**Comment by sandraVicom** [comment]
My problem was that the ionic view doesn't recognise the couchbaseLite phonegap plugin. So I can't run it on ionic view, I run it directly at the device.

**Comment by yueyingcui** [comment]
Thank you very much for reply! I use the phonegap developer app (https://play.google.com/store/apps/details?id=com.adobe.phonegap.app), and it doesn't recognise the couchbaseLite phonegap plugin too.
