### ISSUE TITLE
Update View doesn't update the index

### ISSUE THREAD

**Issue by jdupouy** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#51]
Hi,

When I update a view using the rest API the index is not updated. This then gives strange results mixing the indexes of the old views with the new one. Is this a normal behavior or am I missing something ?

The only way I found to update a view was to rename it (_view/foo1 becomes _view/foo2). But this implies to rename all the calls to the view as well.

Regards.

**Comment by Crapulax** [comment]
I have observed the same issue. It looks like the view is accessed in stale mode... Only new docs get mapped with the new view definition as the view is not recreated.

**Comment by hideki** [comment]
This issue will be tracked by https://github.com/couchbase/couchbase-lite-android/issues/1139
