### ISSUE TITLE
Broken Link:  "ask it what URL it has launched on for subsequent XHR access"

### ISSUE THREAD

**Issue by WilliamHoang** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#54]
Link behind: "ask it what URL it has launched on for subsequent XHR access" : 
https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/blob/master/www/litegap-example.html

**Comment by jamiltz** [comment]
https://github.com/couchbaselabs/couchbase-lite-phonegap-plugin-builder/commit/54063c93ea462d0edb3eeea3bc34402b0a263f95
