### ISSUE TITLE
iOS app Crash with 1.1.0

### ISSUE THREAD

**Issue by lucapale** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#56]
Hi,
after I have upgraded to 1.1.0 the app crashes with the following error:
2015-09-05 12:38:34.674 DivePlan[5271:22369519] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010964fc65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010d57dbb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010964fb9d +[NSException raise:format:] + 205
    3   Foundation                          0x000000010d21bc26 _writeJSONNumber + 748
    4   Foundation                          0x000000010d217efc _writeJSONValue + 477
    5   Foundation                          0x000000010d21c46f ___writeJSONObject_block_invoke + 220
    6   CoreFoundation                      0x000000010958f656 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
    7   CoreFoundation                      0x000000010958f55c -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 204
    8   Foundation                          0x000000010d21c080 _writeJSONObject + 376
    9   Foundation                          0x000000010d217ea6 _writeJSONValue + 391
    10  Foundation                          0x000000010d217cea -[_NSJSONWriter dataWithRootObject:options:error:] + 137
    11  Foundation                          0x000000010d21a76b +[NSJSONSerialization dataWithJSONObject:options:error:] + 345
    12  DivePlan                            0x000000010912be44 +[CBLJSON dataWithJSONObject:options:error:] + 172
    13  DivePlan                            0x000000010913b887 -[CBL_SQLiteViewStorage _emitKey:value:valueIsDoc:forSequence:] + 180
    14  DivePlan                            0x000000010913b540 __39-[CBL_SQLiteViewStorage updateIndexes:]_block_invoke159 + 97
    15  DivePlan                            0x00000001090aab57 -[CBLJSViewCompiler emitWithKey:value:] + 38
    16  DivePlan                            0x00000001090aaac6 __25-[CBLJSViewCompiler init]_block_invoke + 79
    17  CoreFoundation                      0x0000000109545dec __invoking_** + 140
    18  CoreFoundation                      0x0000000109545c42 -[NSInvocation invoke] + 290
    19  JavaScriptCore                      0x000000010cca2a61 _ZN3JSC24ObjCCallbackFunctionImpl4callEP9JSContextP13OpaqueJSValuemPKPKS3_PS6_ + 433
    20  JavaScriptCore                      0x000000010cca25d6 _ZN3JSCL34objCCallbackFunctionCallAsFunctionEPK15OpaqueJSContextP13OpaqueJSValueS4_mPKPKS3_PS6_ + 262
    21  JavaScriptCore                      0x000000010cca3775 _ZN3JSC19APICallbackFunction4callINS_20ObjCCallbackFunctionEEExPNS_9ExecStateE + 517
    22  JavaScriptCore                      0x000000010cb7c38e _ZN3JSC14handleHostCallEPNS_9ExecStateENS_7JSValueENS_22CodeSpecializationKindE + 542
    23  JavaScriptCore                      0x000000010cb7c542 linkFor + 162
    24  ???                                 0x00000334d2dc4d64 0x0 + 3525410835812
    25  ???                                 0x00000334d2dc86f0 0x0 + 3525410850544
    26  JavaScriptCore                      0x000000010cc6f881 callToJavaScript + 311
    27  JavaScriptCore                      0x000000010cb53ea3 _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 35
    28  JavaScriptCore                      0x000000010cb368a0 _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 480
    29  JavaScriptCore                      0x000000010c972fde _ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 62
    30  JavaScriptCore                      0x000000010cbf7190 JSObjectCallAsFunction + 688
    31  JavaScriptCore                      0x000000010cc2993e -[JSValue callWithArguments:] + 286
    32  DivePlan                            0x00000001090aa7b0 -[CBLJSFunction call:] + 357
    33  DivePlan                            0x00000001090aacb1 __49-[CBLJSViewCompiler compileMapFunction:language:]_block_invoke + 63
    34  DivePlan                            0x000000010913ad6e __39-[CBL_SQLiteViewStorage updateIndexes:]_block_invoke + 6605
    35  DivePlan                            0x000000010912fd26 -[CBL_SQLiteStorage inTransaction:] + 100
    36  DivePlan                            0x000000010913926f -[CBL_SQLiteViewStorage updateIndexes:] + 225
    37  DivePlan                            0x00000001090c533c -[CBLView updateIndexes:] + 78
    38  DivePlan                            0x00000001090c5268 -[CBLView updateIndex] + 57
    39  DivePlan                            0x00000001091616ac -[CBL_Router(Handlers) queryDesignDoc:view:keys:] + 550
    40  DivePlan                            0x0000000109161ab3 -[CBL_Router(Handlers) do_GET:designDocID:view:] + 53
    41  DivePlan                            0x00000001091585ca -[CBL_Router route] + 3367
    42  DivePlan                            0x0000000109158b61 -[CBL_Router run] + 859
    43  Foundation                          0x000000010d12f69a __NSThreadPerformPerform + 299
    44  CoreFoundation                      0x0000000109583431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    45  CoreFoundation                      0x00000001095792fd **CFRunLoopDoSources0 + 269
    46  CoreFoundation                      0x0000000109578934 __CFRunLoopRun + 868
    47  CoreFoundation                      0x0000000109578366 CFRunLoopRunSpecific + 470
    48  Foundation                          0x000000010d133f92 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 275
    49  DivePlan                            0x00000001090b0fe5 -[CBL_Server runServerThread] + 315
    50  Foundation                          0x000000010d13209d __NSThread__main** + 1194
    51  libsystem_pthread.dylib             0x000000010dcfc05a _pthread_body + 131
    52  libsystem_pthread.dylib             0x000000010dcfbfd7 _pthread_body + 0
    53  libsystem_pthread.dylib             0x000000010dcf93ed thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

If I go back to 1.0.4 everything works fine.
Any idea how to solve it?
Thanks
![schermata 2015-09-05 alle 12 40 43](https://cloud.githubusercontent.com/assets/1853747/9698898/dbf74270-53cb-11e5-915e-59b1bbf4a2be.png)

**Comment by Crapulax** [comment]
Hello,

From the stack you sent, it looks like you have a document in the DB, with a field used as a view key, which cannot be parsed as a number.
What I would suggest is to drop views one by one to identify the offending view. Then parse all documents on the failing view to see the doc content of the not a number field.

Hope it helps
