### ISSUE TITLE
cblite plugin can not be found after upgraded to 1.1.1 version

### ISSUE THREAD

**Issue by HanzhiDou** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#57]
Hello,
I upgraded xcode to 7 and also this plugin to latest 1.1.1 version, the whole cbl does not work due to window.cblite plugin can not be found.  Then I restored the cblite plugin to the 1.1 version, my app works again, nothing else is changed.

What could be the problem?

BTW, I could not understand why not keep revisions in this repository? how can I get an earlier version?

Thanks!

**Comment by malloc32** [comment]
Try to add manually all necessary files in XCode build phases:
 - Compile sources:
         CBLite.m
 - Link binary with libraries:
         CouchbaseLite.a
         CouchbaseLiteListener.a
         libicucore.dylib
         libz.dylib
         libsqllite3.dylib

**Comment by HanzhiDou** [comment]
seems some envs problem in my computer, I uninstalled previous version and tried again today, now it works.
