### ISSUE TITLE
Question: What is the Proper way to cancel continuous replication?

### ISSUE THREAD

**Issue by jfspencer** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#61]
The REST API docs do not mention how to cancel a continuous replication. The CouchDB docs mention passing in a JSON object to the _replicate end point like so -

```
{'replication_id':'theId', 'cancel':true}
```

CBL docs mention a session_id being returned when replication is started. So should I pass in this instead? 

```
{'session_id':'theId', 'cancel':true}
```

**Comment by Crapulax** [comment]
Hi,

You need to pass session_id field (from replication start answer) with cancel field set to true. Below code we are using:

// when you start
replications[TOSYNC] = {
       continuous: true,
       source: localdbname,
       target: {headers: headerKey.headers, url: myContext.syncURL + myContext.syncDBName}
                };
// get session id from the replication start response
 if (result.hasOwnProperty('session_id')) {
                                sessionid = result.session_id;
                            } else {
                                sessionid = result._local_id;
                            }
// and store it
replications[TOSYNC].session_id = sessionid;

//to cancel send exactly above with cancel field set
                        replications[TOSYNC].cancel = true;

brgds
