### ISSUE TITLE
Build Failed after installing plugin

### ISSUE THREAD

**Issue by vikas009** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#64]
Hi, I am building an app using ionic framework and couchbase by following tutorial http://blog.couchbase.com/using-couchbase-in-your-ionic-framework-application-part-1 

project builds fine without the plugin installed but after installing plugin build fails with following error : 

![couchbaseplugin error](https://cloud.githubusercontent.com/assets/16116073/11529437/0ba3d9ca-9913-11e5-97d1-15621e86f9aa.png)

cordova version : 5.4.1
Ionic Version : 1.7.10

**Comment by WorldMaker** [comment]
I'm seeing this as well. Looking at the [latest Cordova Android documentation](http://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html) it seems like the plugin.xml has changed and `source-file` tags should be changed to `framework` and `lib-file` tags in the new build system, maybe?

**Comment by vikas009** [comment]
I got it working by following below hack :-

Create <b>platforms/android/build-extras.gradle</b> file in your project and add the following lines in it:

```javascript
android {
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}
```

Let me know if it solves your issue as well... :)

**Comment by pasin** [comment]
I believe this should be working in 1.1.1 and 1.2.0 release.
