### ISSUE TITLE
couchbase lite plugin no more working after updating to 1.1.1 (from 1.0.4) on android

### ISSUE THREAD

**Issue by zeprone** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#65]
Each time I am trying to insert a new element I have the following error:

"E/View﹕ Error emitting
    com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.mozilla.javascript.Undefined and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )"

E/View﹕ Error emitting
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.mozilla.javascript.Undefined and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )

**Comment by pasin** [comment]
Could you please try with 1.2 release?

**Comment by snej** [comment]
This is caused by accidentally passing a JS `undefined` value to the `emit` function. `undefined` is not valid JSON. You'll need to preflight whether a property exists before trying to emit it.

**Comment by zeprone** [comment]
Hi, thx for your replies, I am no more using cb-lite for my ongoing project, but be sure I will try both your solutions on a my sandbox project asap.
