### ISSUE TITLE
Cannot deploy Android application to emulators

### ISSUE THREAD

**Issue by PreslavKozovski** [couchbaselabs/Couchbase-Lite-PhoneGap-Plugin#85]
Cannot deploy on both Android Studio and Genymotion emulators with the following error:
`INSTALL_FAILED_NO_MATCHING_ABIS`
when using **x86/x86_64** CPU/ABI. 

Was able to deploy to emulators using **armeabi-v7a** architecture. Additionally, I was able to deploy to any emulators with Couchbase-Lite plugin version 1.0.5

Cordova for Android: 4.1.1/5.1.0/5.2.1
Android: 4.4/5.1/6.0
Couchbase-Lite plugin: 1.3.0/1.3.1

**Comment by mb34124** [comment]
I'm having the same problem.  Was x86/x86_64 support removed at some point?

**Comment by mb34124** [comment]
Any update on this?

**Comment by pasin** [comment]
@hideki do you have any idea on this issue?

**Comment by hideki** [comment]
I don't have no idea. I will test this scenario today.

**Comment by hideki** [comment]
Hi All,

With following instruction of https://github.com/couchbaselabs/TodoLite-PhoneGap, I can successfully deploy phoneGap app to Genymotion.

Genytmotion Version: 2.8.0
Android Version : 5.0.0 - API 21

Note: I believe Genymotion only supports `x86`.

**Comment by hideki** [comment]
I also installed ToDoLite PhoneGap sample to Android Stack emulator. Emulator is Android 7.0 with x86 emulation. I don't have any installation issue with this environment.
